"""kullaniciEv

Revision ID: e30a6e339b39
Revises: 9417d341c51d
Create Date: 2024-01-11 18:50:36.592259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30a6e339b39'
down_revision = '9417d341c51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birim')
    op.drop_table('kurumtur')
    op.drop_table('kurum')
    op.drop_table('bolum')
    with op.batch_alter_table('kullanici_okul', schema=None) as batch_op:
        batch_op.add_column(sa.Column('okul_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('kullanici_okul_rol_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'okul', ['okul_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('rol_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici_okul', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kullanici_okul_rol_id_fkey', 'rol', ['rol_id'], ['id'])
        batch_op.drop_column('okul_id')

    op.create_table('bolum',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('birim_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['birim_id'], ['birim.id'], name='bolum_birim_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bolum_pkey')
    )
    op.create_table('kurum',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('kurum_tur_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kurum_tur_id'], ['kurumtur.id'], name='kurum_kurum_tur_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='kurum_pkey')
    )
    op.create_table('kurumtur',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kurumtur_pkey')
    )
    op.create_table('birim',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('birim_ad', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='birim_pkey')
    )
    # ### end Alembic commands ###
